language: node_js
node_js:
  - node
cache: yarn
before_script:
 - yarn global add expo-cli
jobs:
  include:
    - stage: typecheck
      script: yarn run check
    - stage: test
      script: yarn test
    - stage: lint
      script: yarn run lint
    - stage: deploy
      deploy:
      - provider: script
        script: bash scripts/deploy.sh $EXPO_USERNAME $EXPO_PASSWORD staging
        skip_cleanup: true
        on:
          branch: master
      - provider: script
        script: scripts/deploy.sh $EXPO_USERNAME $EXPO_PASSWORD default
        skip_cleanup: true
        on:
          branch: stable