# Javascript Node CircleCI 2.0 configuration file
version: 2
jobs:
    doctor:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install dependencies
                command: npm i
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run: npm run doctor -s

    test:
        docker:
            - image: circleci/node:latest

        steps:
            - checkout
            - restore_cache:
                keys:
                    - dependency-cache-{{ checksum "package.json" }}
                    - dependency-cache-
            - run: 
                name: Install Dependencies
                command: npm i
            - save_cache:
                paths:
                    - node_modules
                    - .jest
                key: dependency-cache-{{ checksum "package.json" }}
            - run: 
                name: Run Tests
                command: npm run ci-test -s

    lint:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run: npm run lint -s

    audit:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run: npm audit

workflows:
    version: 2
    tests:
        jobs:
            - test
            - lint
    audits:
        jobs:
            - doctor
            - audit