version: 2
jobs:
    test:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - attach_workspace:
                at: "."
            - run:
                name: Install JUnit coverage reporter
                command: npm i -D jest-junit
            - run:
                name: Run tests with JUnit as reporter
                command: npm run test:ci -s
                environment:
                    JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
                

    lint:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - attach_workspace:
                at: "."
            - run: 
                name: TSLint
                command: npm run lint -s

    compile:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - attach_workspace:
                at: "."
            - run: 
                name: TypeScript Compile
                command: npm run compile -s

    install-deps:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                name: Update NPM
                command: sudo npm i -g npm@latest
            - run: 
                name: Install Dependencies
                command: npm ci
            - run:
                name: Audit
                command: npm audit
            - save_cache:
                paths:
                    - node_modules
                    - package-lock.json
                    - ~/.npm
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - persist_to_workspace:
                    root: "."
                    paths:
                        - node_modules
                        - package-lock.json

workflows:
    version: 2
    test-lint-compile:
        jobs:
            - install-deps
            - test:
                requires:
                    - install-deps
            - lint:
                requires:
                    - install-deps
            - compile:
                requires:
                    - install-deps
            
