version: 2
jobs:
    doctor:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - attach_workspace:
                at: "."
            - run: 
                name: Doctor
                command: npm run doctor -s

    test:
        docker:
            - image: circleci/node:latest

        steps:
            - checkout
            - attach_workspace:
                at: "."
            - run: 
                name: Run Tests
                command: npm run ci-test -s

    lint:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - attach_workspace:
                at: "."
            - run: 
                name: TSLint
                command: npm run lint -s

    audit:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - attach_workspace:
                at: "."
            - run: 
                name: NPM Audit
                command: npx audit-ci

    compile:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - attach_workspace:
                at: "."
            - run: 
                name: TypeScript Compile
                command: npm run compile -s

    install-deps:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Update NPM
                command: sudo npm i -g npm@latest
            - run: 
                name: Install Dependencies
                command: npm i
            - run:
                name: Create Package Lock
                command: npm i --package-lock-only
            - save_cache:
                paths:
                    - node_modules
                    - package-lock.json
                key: dependency-cache-{{ checksum "package.json" }}
            - persist_to_workspace:
                    root: "."
                    paths:
                        - node_modules
                        - package-lock.json

workflows:
    version: 2
    test:
        jobs:
            - install-deps
            - doctor:
                requires:
                    - install-deps
            - audit:
                requires:
                    - install-deps
            - test:
                requires:
                    - install-deps
                    - doctor
                    - audit
    lint:
        jobs:
            - install-deps
            - lint:
                requires:
                    - install-deps
    compile:
        jobs:
            - install-deps
            - compile:
                requires:
                    - install-deps
