name: Build App
on: [push]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com/
          scope: "@whsha"
      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: /home/runner/.cache/yarn/v6
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache node
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: yarn run typecheck
  test:
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com/
          scope: "@whsha"
      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: /home/runner/.cache/yarn/v6
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache node
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: yarn run testcov --forceExit
      - uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.codecov_token}}
  lint:
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com/
          scope: "@whsha"
      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: /home/runner/.cache/yarn/v6
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache node
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: yarn run lint
      - run: yarn run exportlint
  deploy:
    runs-on: ubuntu-latest
    needs: [test, lint, typecheck]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com/
          scope: "@whsha"
      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: /home/runner/.cache/yarn/v6
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache node
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Fix inotify max_user_watches
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Install Sentry CLI
        run: curl -sL https://sentry.io/get-cli/ | bash
      - name: Publish
        run: sh .github/workflows/publish.sh
        env:
          # Expo data
          EXPO_USERNAME: dusterthefirst
          EXPO_PASSWORD: ${{ secrets.expo_password }}
          # Branch info
          IS_MASTER: ${{github.ref == 'refs/heads/master'}}
          IS_STABLE: ${{github.ref == 'refs/heads/stable'}}
          # Sentry data
          SENTRY_ORG: dusterthefirst
          SENTRY_AUTH_TOKEN: ${{secrets.sentry_auth_token}}
          # Webhook data
          COMMIT_MESSAGE: ${{github.event.commits[0].message}}
          SENDER_USERNAME: ${{github.events.sender.login}}
          SENDER_URL: ${{github.events.sender.url}}
          SENDER_AVATAR: ${{github.events.sender.avatar_url}}
          # Webhook urls
          WEBHOOK_URL: ${{secrets.release_webhook}}
          ALPHA_WEBHOOK_URL: ${{secrets.alpha_release_webhook}}
          STABLE_WEBHOOK_URL: ${{secrets.stable_release_webhook}}
