name: Build App
on:
  push:
    paths:
      - '*.ts'
      - '*.tsx'
      - '*.json'
      - 'src/*'
      - 'assets/*'
      - 'typings/*'
      - '.github/workflows/*'
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn run check
  test:
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn run test
  lint:
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn run lint
  deploy:
    runs-on: ubuntu-latest
    needs: [test, lint, typecheck]
    steps:
      - run: yarn global add expo-cli
      - uses: actions/checkout@v1
      - run: yarn
      - name: Fix inotify max_user_watches
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Install Sentry CLI
        run: curl -sL https://sentry.io/get-cli/ | bash
      - name: Publish
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/stable')
        run: sh .github/workflows/publish.sh
        env:
          EXPO_USERNAME:      ${{ secrets.expo_username }}
          EXPO_PASSWORD:      ${{ secrets.expo_password }}
          IS_MASTER:          ${{github.ref == 'refs/heads/master'}}
          IS_STABLE:          ${{github.ref == 'refs/heads/stable'}}
          SENTRY_ORG:         dusterthefirst
          SENTRY_AUTH_TOKEN:  ${{secrets.sentry_auth_token}}
  # collect_metadata:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
