name: Check Pull Request
on: [pull_request]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn run typecheck
  test:
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn run testcov
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.codecov_token}}
  lint:
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn run lint